# Model Code

In [1]:
import numpy as np
nsd_train_cap_sub1 = np.load('nsd_train_cap_sub1.npy', allow_pickle=True)
nsd_train_fmriavg_nsdgeneral_sub1 = np.load('nsd_train_fmriavg_nsdgeneral_sub1.npy', allow_pickle=True)
nsd_test_cap_sub1 = np.load('nsd_test_cap_sub1.npy', allow_pickle=True)
nsd_test_fmriavg_nsdgeneral_sub1 = np.load('nsd_test_fmriavg_nsdgeneral_sub1.npy', allow_pickle=True)

In [2]:
X_train_fmri = nsd_train_fmriavg_nsdgeneral_sub1
X_test_fmri = nsd_test_fmriavg_nsdgeneral_sub1

In [3]:
type(X_train_fmri)

numpy.ndarray

In [4]:
X_train_fmri.shape

(8859, 15724)

In [5]:
X_train_fmri[0].shape

(15724,)

In [6]:
X_train_fmri[0].min(), X_train_fmri[0].max()

(-3784.333251953125, 11740.0)

In [7]:
np.random.randint(2, size=10).reshape(10,1)

array([[0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1]])

In [8]:
no_of_y = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
made_up_y = []

for i in no_of_y:
    y_vector = np.random.randint(2, size=10)#.reshape(10,1)
    made_up_y.append(y_vector)

In [10]:
made_up_y 

[array([1, 1, 0, 0, 0, 1, 0, 0, 0, 1]),
 array([0, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 1, 1, 0, 1, 1, 1, 0, 1, 0]),
 array([0, 0, 1, 1, 1, 1, 1, 1, 0, 1]),
 array([1, 0, 0, 1, 1, 0, 1, 0, 1, 0]),
 array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1]),
 array([0, 1, 1, 0, 1, 0, 1, 0, 0, 0]),
 array([1, 1, 0, 1, 0, 0, 1, 0, 0, 1]),
 array([0, 1, 1, 0, 1, 1, 0, 1, 0, 1]),
 array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1])]

In [11]:
type(made_up_y[0])

numpy.ndarray

In [12]:
sliced_X_train = X_train_fmri[0:10]

In [13]:
sliced_X_train[0]

array([-208.66667175,   10.33333302,  222.        , ...,  508.        ,
       1158.        ,  771.66668701])

In [14]:
len(sliced_X_train)

10

In [15]:
from tensorflow.keras import Sequential, layers, models


In [16]:
model = models.Sequential()

model.add(layers.Dense(5, activation='relu', input_dim=15724)) 
model.add(layers.Dense(4, activation='relu')) 
model.add(layers.Dense(3, activation='relu')) 

model.add(layers.Dense(10, activation='sigmoid'))



In [17]:
model.compile(optimizer='rmsprop',
    loss='binary_crossentropy')

In [18]:
sliced_X_train.shape

(10, 15724)

In [19]:
made_up_y = np.array(made_up_y)

In [20]:
history = model.fit(sliced_X_train,
          made_up_y, 
          validation_split = 0.3,
          epochs=30)

Epoch 1/30
1/1 [==============================] - 0s 250ms/step - loss: 9.7129 - val_loss: 0.6934
Epoch 2/30
1/1 [==============================] - 0s 8ms/step - loss: 0.6929 - val_loss: 0.6932
Epoch 3/30
1/1 [==============================] - 0s 10ms/step - loss: 0.6927 - val_loss: 0.6931
Epoch 4/30
1/1 [==============================] - 0s 9ms/step - loss: 0.6925 - val_loss: 0.6930
Epoch 5/30
1/1 [==============================] - 0s 10ms/step - loss: 0.6923 - val_loss: 0.6929
Epoch 6/30
1/1 [==============================] - 0s 10ms/step - loss: 0.6921 - val_loss: 0.6929
Epoch 7/30
1/1 [==============================] - 0s 11ms/step - loss: 0.6920 - val_loss: 0.6928
Epoch 8/30
1/1 [==============================] - 0s 11ms/step - loss: 0.6918 - val_loss: 0.6927
Epoch 9/30
1/1 [==============================] - 0s 9ms/step - loss: 0.6916 - val_loss: 0.6926
Epoch 10/30
1/1 [==============================] - 0s 11ms/step - loss: 0.6915 - val_loss: 0.6926
Epoch 11/30
1/1 [==============

In [21]:
result = model.predict(sliced_X_train[8:11])

1/1 [==============================] - 0s 43ms/step


In [22]:
result[0]

array([0.49203265, 0.49201334, 0.50798666, 0.49203265, 0.50936204,
       0.49203265, 0.50936204, 0.49201334, 0.49201313, 0.5079674 ],
      dtype=float32)

In [23]:
result[0].shape

(10,)