# Modelling

## Imports

In [1]:
import pandas as pd
import numpy as np
from tensorflow.keras import Sequential, layers, models
from sklearn.preprocessing import MinMaxScaler, RobustScaler

## y_train and y_test

In [2]:
y_dataframe = pd.read_csv('../raw_data/y_dataframe_2.csv', index_col=0)

/var/folders/fy/tmxs8hm12_57zw_rkkvx7c7w0000gn/T/ipykernel_59232/2686232150.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  y_dataframe = pd.read_csv('../raw_data/y_dataframe_2.csv', index_col=0)


In [3]:
y_dataframe

Unnamed: 1  1950  1950s  1970  1971  2009  2010  4way  abandon  \
0                       0     0      0     0     0     0     0     0        0   
1                       0     0      0     0     0     0     0     0        0   
2                       0     0      0     0     0     0     0     0        0   
3                       0     0      0     0     0     0     0     0        0   
4                       0     0      0     0     0     0     0     0        0   
...                   ...   ...    ...   ...   ...   ...   ...   ...      ...   
X_test_id_977           0     0      0     0     0     0     0     0        0   
X_test_id_978           0     0      0     0     0     0     0     0        0   
X_test_id_979           0     0      0     0     0     0     0     0        0   
X_test_id_980           0     0      0     0     0     0     1     0        0   
X_test_id_981           0     0      0     0     0     0     0     0        0   

               ability  ...  young  younger  youre  youth  zebra  zigzag  zip  \
0                    0  ...      0        0      0      0      0       0    0   
1                    0  ...      0        0      0      0      0       0    0   
2                    0  ...      0        0      0      0      0       0    0   
3                    0  ...      0        0      0      0      0       0    0   
4                    0  ...      0        0      0      0      1       0    0   
...                ...  ...    ...      ...    ...    ...    ...     ...  ...   
X_test_id_977        0  ...      0        0      0      0      0       0    0   
X_test_id_978        0  ...      0        0      0      0      0       0    0   
X_test_id_979        0  ...      0        0      0      0      0       0    0   
X_test_id_980        0  ...      0        0      0      0      0       0    0   
X_test_id_981        0  ...      0        0      0      0      0       0    0   

               zombie  zoo  zoom  
0                   0    0     0  
1                   0    0     0  
2                   0    0     0  
3                   0    0     0  
4                   0    0     0  
...               ...  ...   ...  
X_test_id_977       0    0     0  
X_test_id_978       0    0     0  
X_test_id_979       0    0     0  
X_test_id_980       0    0     0  
X_test_id_981       0    0     0  

[9841 rows x 3760 columns]

In [4]:
y_dataframe.drop(columns = 'Unnamed: 1', inplace=True)

In [5]:
y_dataframe

1950  1950s  1970  1971  2009  2010  4way  abandon  ability  \
0                 0      0     0     0     0     0     0        0        0   
1                 0      0     0     0     0     0     0        0        0   
2                 0      0     0     0     0     0     0        0        0   
3                 0      0     0     0     0     0     0        0        0   
4                 0      0     0     0     0     0     0        0        0   
...             ...    ...   ...   ...   ...   ...   ...      ...      ...   
X_test_id_977     0      0     0     0     0     0     0        0        0   
X_test_id_978     0      0     0     0     0     0     0        0        0   
X_test_id_979     0      0     0     0     0     0     0        0        0   
X_test_id_980     0      0     0     0     0     1     0        0        0   
X_test_id_981     0      0     0     0     0     0     0        0        0   

               ablaze  ...  young  younger  youre  youth  zebra  zigzag  zip  \
0                   0  ...      0        0      0      0      0       0    0   
1                   0  ...      0        0      0      0      0       0    0   
2                   0  ...      0        0      0      0      0       0    0   
3                   0  ...      0        0      0      0      0       0    0   
4                   0  ...      0        0      0      0      1       0    0   
...               ...  ...    ...      ...    ...    ...    ...     ...  ...   
X_test_id_977       0  ...      0        0      0      0      0       0    0   
X_test_id_978       0  ...      0        0      0      0      0       0    0   
X_test_id_979       0  ...      0        0      0      0      0       0    0   
X_test_id_980       0  ...      0        0      0      0      0       0    0   
X_test_id_981       0  ...      0        0      0      0      0       0    0   

               zombie  zoo  zoom  
0                   0    0     0  
1                   0    0     0  
2                   0    0     0  
3                   0    0     0  
4                   0    0     0  
...               ...  ...   ...  
X_test_id_977       0    0     0  
X_test_id_978       0    0     0  
X_test_id_979       0    0     0  
X_test_id_980       0    0     0  
X_test_id_981       0    0     0  

[9841 rows x 3759 columns]

In [6]:
y_train = y_dataframe.iloc[0:8859].to_numpy()

In [7]:
y_test = y_dataframe.iloc[8859:9842].to_numpy()

In [8]:
y_train.shape

(8859, 3759)

In [9]:
y_test.shape

(982, 3759)

## X_train and X_test

In [10]:
X_train = np.load('../raw_data/nsd_train_fmriavg_nsdgeneral_sub1.npy')

In [11]:
X_test = np.load('../raw_data/nsd_test_fmriavg_nsdgeneral_sub1.npy')

In [12]:
X_train[0]

array([-208.66667175,   10.33333302,  222.        , ...,  508.        ,
       1158.        ,  771.66668701])

In [13]:
X_train.shape

(8859, 15724)

In [14]:
X_test.shape

(982, 15724)

In [15]:
scaler = RobustScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Modelling

In [16]:

model = models.Sequential()

model = Sequential([layers.Dense(100, input_shape = (15724,), activation = "relu"),
                  layers.Dense(100, activation = "relu"),
                    layers.Dropout(0.4),
                  layers.Dense(200, activation = "relu"),
                    layers.Dropout(0.4),
                  layers.Dense(500, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(5000, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(1000, activation = "relu"),
                    layers.Dropout(0.4),
                     layers.Dense(2000, activation = "relu"),
                    layers.Dropout(0.4),
                  layers.Dense(800, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(5000, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(1000, activation = "relu"),
                    layers.Dropout(0.4),
                     layers.Dense(900, activation = "relu"),
                    layers.Dropout(0.4),
                  layers.Dense(1000, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(5000, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(1000, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(2000, activation = "relu"),
                  layers.Dense(3759, activation = "sigmoid")])


# model.add(layers.Dense(2637, activation='sigmoid'))

In [17]:
model.compile(optimizer='adam',
    loss='binary_crossentropy',
             metrics = ['accuracy'])

In [18]:
history = model.fit(X_train_scaled,
                    y_train, 
                    validation_split = 0.1,
                    batch_size = 32,
                    epochs=30)

Epoch 1/30
250/250 [==============================] - 20s 77ms/step - loss: 0.0214 - accuracy: 0.0014 - val_loss: 0.0104 - val_accuracy: 0.0000e+00
Epoch 2/30
250/250 [==============================] - 18s 72ms/step - loss: 0.0105 - accuracy: 0.0020 - val_loss: 0.0105 - val_accuracy: 0.0000e+00
Epoch 3/30
250/250 [==============================] - 18s 73ms/step - loss: 0.0105 - accuracy: 0.0019 - val_loss: 0.0103 - val_accuracy: 0.0000e+00
Epoch 4/30
250/250 [==============================] - 18s 72ms/step - loss: 0.0105 - accuracy: 0.0013 - val_loss: 0.0103 - val_accuracy: 0.0090
Epoch 5/30
250/250 [==============================] - 18s 73ms/step - loss: 0.0104 - accuracy: 0.0028 - val_loss: 0.0103 - val_accuracy: 0.0090
Epoch 6/30
250/250 [==============================] - 18s 73ms/step - loss: 0.0104 - accuracy: 0.0016 - val_loss: 0.0103 - val_accuracy: 0.0000e+00
Epoch 7/30
250/250 [==============================] - 18s 73ms/step - loss: 0.0104 - accuracy: 8.7796e-04 - val_loss: 0.

In [19]:
# answer = model.predict(X_train_scaled[10].reshape(1,-1))

In [20]:
# answer[answer>0.1]

In [21]:
# answer_idxs = np.argpartition(answer[0],-4)[-4:]

In [22]:
# answer_idxs

In [23]:
# y_dataframe

In [32]:
labels = y_dataframe.columns[0:]

In [33]:
labels

Index(['1950', '1950s', '1970', '1971', '2009', '2010', '4way', 'abandon',
       'ability', 'ablaze',
       ...
       'young', 'younger', 'youre', 'youth', 'zebra', 'zigzag', 'zip',
       'zombie', 'zoo', 'zoom'],
      dtype='object', length=3759)

In [26]:
# labels[answer_idxs]

In [39]:
test_answer = model.predict(X_test_scaled[800].reshape(1,-1))

1/1 [==============================] - 0s 18ms/step


In [40]:
test_answer

array([[5.0800958e-05, 2.1925445e-04, 6.8525645e-05, ..., 6.7792484e-05,
        6.1545690e-04, 1.9322995e-04]], dtype=float32)

In [41]:
test_answer_idxs = np.argpartition(test_answer[0],-4)[-4:]

In [42]:
test_answer_idxs

array([3167, 2161, 3670, 2940])

In [43]:
labels[test_answer_idxs]

Index(['street', 'next', 'white', 'sit'], dtype='object')