In [85]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, RobustScaler

In [31]:
from tensorflow.keras import Sequential, layers, models

### To get the data for X_train, y_train, X_test, y_test

In [26]:
y_dataframe = pd.read_csv('../data/dataframes/y_dataframe.csv',index_col = 0)

/var/folders/9w/z8lx7y0n7b198wy4jq4t4zrh0000gn/T/ipykernel_3758/3183250962.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  y_dataframe = pd.read_csv('../data/dataframes/y_dataframe.csv',index_col = 0)


In [94]:
y_dataframe.index

Index([              0,               1,               2,               3,
                     4,               5,               6,               7,
                     8,               9,
       ...
       'X_test_id_972', 'X_test_id_973', 'X_test_id_974', 'X_test_id_975',
       'X_test_id_976', 'X_test_id_977', 'X_test_id_978', 'X_test_id_979',
       'X_test_id_980', 'X_test_id_981'],
      dtype='object', length=9841)

In [6]:
y_train = y_dataframe.iloc[0:8859].to_numpy()

In [7]:
y_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [8]:
y_train.shape

(8859, 2637)

In [9]:
y_test = y_dataframe.iloc[8859:].to_numpy()

In [10]:
y_test.shape

(982, 2637)

In [11]:
X_train = np.load('../data/nsd_train_fmriavg_nsdgeneral_sub1.npy')

In [12]:
X_train.shape

(8859, 15724)

In [13]:
X_test = np.load('../data/nsd_test_fmriavg_nsdgeneral_sub1.npy')

In [14]:
X_test.shape

(982, 15724)

#### To get a new y_train and y_test on a bigger vocabulary

In [25]:
y_dataframe_2 = pd.read_csv('../data/dataframes/y_dataframe_2.csv',index_col = 0)

/var/folders/9w/z8lx7y0n7b198wy4jq4t4zrh0000gn/T/ipykernel_3758/3702576093.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  y_dataframe_2 = pd.read_csv('../data/dataframes/y_dataframe_2.csv',index_col = 0)


In [28]:
y_dataframe_2

Unnamed: 1  1950  1950s  1970  1971  2009  2010  4way  abandon  \
0                       0     0      0     0     0     0     0     0        0   
1                       0     0      0     0     0     0     0     0        0   
2                       0     0      0     0     0     0     0     0        0   
3                       0     0      0     0     0     0     0     0        0   
4                       0     0      0     0     0     0     0     0        0   
...                   ...   ...    ...   ...   ...   ...   ...   ...      ...   
X_test_id_977           0     0      0     0     0     0     0     0        0   
X_test_id_978           0     0      0     0     0     0     0     0        0   
X_test_id_979           0     0      0     0     0     0     0     0        0   
X_test_id_980           0     0      0     0     0     0     1     0        0   
X_test_id_981           0     0      0     0     0     0     0     0        0   

               ability  ...  young  younger  youre  youth  zebra  zigzag  zip  \
0                    0  ...      0        0      0      0      0       0    0   
1                    0  ...      0        0      0      0      0       0    0   
2                    0  ...      0        0      0      0      0       0    0   
3                    0  ...      0        0      0      0      0       0    0   
4                    0  ...      0        0      0      0      1       0    0   
...                ...  ...    ...      ...    ...    ...    ...     ...  ...   
X_test_id_977        0  ...      0        0      0      0      0       0    0   
X_test_id_978        0  ...      0        0      0      0      0       0    0   
X_test_id_979        0  ...      0        0      0      0      0       0    0   
X_test_id_980        0  ...      0        0      0      0      0       0    0   
X_test_id_981        0  ...      0        0      0      0      0       0    0   

               zombie  zoo  zoom  
0                   0    0     0  
1                   0    0     0  
2                   0    0     0  
3                   0    0     0  
4                   0    0     0  
...               ...  ...   ...  
X_test_id_977       0    0     0  
X_test_id_978       0    0     0  
X_test_id_979       0    0     0  
X_test_id_980       0    0     0  
X_test_id_981       0    0     0  

[9841 rows x 3760 columns]

In [29]:
y_train_2 = y_dataframe_2.iloc[0:8859].to_numpy()

In [30]:
y_train_2.shape

(8859, 3760)

In [32]:
y_test_2 = y_dataframe_2.iloc[8859:].to_numpy()

In [34]:
y_test_2.shape

(982, 3760)

### To get the caption corresponding to an Image_index

In [15]:
#Load test dataframe
df_test = pd.read_csv('../data/dataframes/df_test.csv')

In [16]:
df_test.head()

Image_index                     test_caps_processed  \
0        46002        ['cow', 'white', 'grass', 'eat']   
1        48617  ['airplane', 'port', 'cloud', 'plane']   
2        44980  ['airplane', 'sky', 'build', 'sunset']   
3        32625    ['kitchen', 'view', 'middle', 'day']   
4        53052     ['clock', 'center', 'tile', 'star']   

                                                fMRI  
0  [-339.66665649 -236.66667175   13.66666698 ......  
1    [ 277.5 -418.    14.5 ...  122.   436.5  461. ]  
2  [ 69.         177.         -49.66666794 ... 28...  
3  [ 366.66665649 -412.           42.33333206 ......  
4  [ -49.33333206 -321.66665649   31.33333397 ......

In [23]:
df_test.shape

(982, 3)

In [17]:
#create new df with just the values you need
df_test_idx_caps= df_test[['Image_index', 'test_caps_processed']]


In [18]:
#Input filename to create index value
filename ='44980.png'
index = filename.split(".")[0]
index = int(index)
index

44980

In [19]:
#fetch caps from index
caps=df_test_idx_caps.loc[df_test_idx_caps['Image_index'] == index, 'test_caps_processed'].item()
print(caps)

['airplane', 'sky', 'build', 'sunset']


### To Build a basic model

In [20]:
scaler = RobustScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [21]:
X_test_scaled

array([[-1.28444441, -0.48185293, -0.05411858, ...,  0.12920738,
        -0.63977899, -0.8584444 ],
       [ 0.08703705, -1.00143268, -0.05013928, ..., -0.09011943,
         0.16381217,  0.49063606],
       [-0.37629628,  0.7034384 , -0.35654596, ...,  0.26167209,
        -0.13701656,  0.43597097],
       ...,
       [ 0.03851854,  0.05682903, -0.55710305, ..., -0.08360478,
         0.68508289, -0.31989202],
       [ 1.98814816,  1.14469915,  1.71906087, ...,  2.5982627 ,
         1.37624311,  1.77425339],
       [-1.50518517, -0.72063038,  0.0620772 , ..., -1.06297501,
        -0.1154696 , -0.36780834]])

In [86]:
X_train_scaled.shape

(8859, 15724)

In [87]:
X_test_scaled.shape

(982, 15724)

In [22]:
X_test

array([[-339.66665649, -236.66667175,   13.66666698, ...,  223.        ,
         -48.33333206, -205.33332825],
       [ 277.5       , -418.        ,   14.5       , ...,  122.        ,
         436.5       ,  461.        ],
       [  69.        ,  177.        ,  -49.66666794, ...,  284.        ,
         255.        ,  434.        ],
       ...,
       [ 255.66667175,  -48.66666794,  -91.66666412, ...,  125.        ,
         751.        ,   60.66666794],
       [1133.        ,  331.        ,  385.        , ..., 1360.        ,
        1168.        , 1095.        ],
       [-439.        , -320.        ,   38.        , ..., -326.        ,
         268.        ,   37.        ]])

In [36]:
# the last layer has 3760 - the size of the vocabulary

In [55]:
model = models.Sequential()

model = Sequential([layers.Dense(200, input_shape = (15724,), activation = "relu"),
                    layers.Dense(200, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(300, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(400, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(400, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(500, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(500, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(1000, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(1000, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(2000, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(2000, activation = "relu"),
                    layers.Dense(3760, activation = "sigmoid")])

In [56]:
model.compile(optimizer='adam',
    loss='binary_crossentropy',
             metrics = ['accuracy'])

In [57]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_41 (Dense)            (None, 200)               3145000   
                                                                 
 dense_42 (Dense)            (None, 200)               40200     
                                                                 
 dropout_29 (Dropout)        (None, 200)               0         
                                                                 
 dense_43 (Dense)            (None, 300)               60300     
                                                                 
 dropout_30 (Dropout)        (None, 300)               0         
                                                                 
 dense_44 (Dense)            (None, 400)               120400    
                                                                 
 dropout_31 (Dropout)        (None, 400)              

In [58]:
history = model.fit(X_train_scaled,
                    y_train_2, 
                    validation_split = 0.1,
                    batch_size = 32,
                    epochs=30)

Epoch 1/30
250/250 [==============================] - 11s 41ms/step - loss: 0.0203 - accuracy: 0.0034 - val_loss: 0.0104 - val_accuracy: 0.0000e+00
Epoch 2/30
250/250 [==============================] - 10s 41ms/step - loss: 0.0105 - accuracy: 0.0010 - val_loss: 0.0103 - val_accuracy: 0.0000e+00
Epoch 3/30
250/250 [==============================] - 10s 41ms/step - loss: 0.0105 - accuracy: 0.0024 - val_loss: 0.0103 - val_accuracy: 0.0000e+00
Epoch 4/30
250/250 [==============================] - 10s 40ms/step - loss: 0.0104 - accuracy: 0.0028 - val_loss: 0.0104 - val_accuracy: 0.0000e+00
Epoch 5/30
250/250 [==============================] - 10s 40ms/step - loss: 0.0104 - accuracy: 0.0026 - val_loss: 0.0103 - val_accuracy: 0.0000e+00
Epoch 6/30
250/250 [==============================] - 10s 40ms/step - loss: 0.0104 - accuracy: 0.0038 - val_loss: 0.0103 - val_accuracy: 0.0000e+00
Epoch 7/30
250/250 [==============================] - 10s 40ms/step - loss: 0.0103 - accuracy: 0.0054 - val_loss

In [61]:
X_test_scaled[10]

array([-0.81333332,  0.89063992, -0.57302029, ..., -0.2290988 ,
        0.45745861, -0.24902988])

In [60]:
X_test_scaled[10].reshape(1,-1)

array([[-0.81333332,  0.89063992, -0.57302029, ..., -0.2290988 ,
         0.45745861, -0.24902988]])

In [62]:
test_answer = model.predict(X_test_scaled[45].reshape(1,-1))

1/1 [==============================] - 0s 96ms/step


In [63]:
test_answer

array([[1.1889849e-02, 6.0950413e-05, 1.7441624e-04, ..., 6.2612082e-05,
        1.3398594e-04, 9.9577424e-05]], dtype=float32)

In [64]:
test_answer_idxs = np.argpartition(test_answer[0],-5)[-5:]

In [65]:
test_answer_idxs

array([3671, 2941, 1305, 3262, 2451])

In [67]:
labels = y_dataframe_2.columns[1:]

In [68]:
labels[test_answer_idxs]

Index(['whitehouse', 'site', 'foot', 'tablecloth', 'plater'], dtype='object')

In [73]:
test_answer_2 = model.predict(X_test_scaled[125].reshape(1,-1))

1/1 [==============================] - 0s 22ms/step


In [77]:
test_answer_idxs_2 = np.argpartition(test_answer_2[0],-5)[-5:]

In [78]:
test_answer_idxs_2

array([3671, 2941, 1305, 3262, 2451])

In [80]:
labels[test_answer_idxs_2]

Index(['whitehouse', 'site', 'foot', 'tablecloth', 'plater'], dtype='object')

In [81]:
test_answer_3 = model.predict(X_test_scaled[500].reshape(1,-1))

1/1 [==============================] - 0s 23ms/step


In [82]:
test_answer_idxs_3 = np.argpartition(test_answer_3[0],-5)[-5:]

In [83]:
test_answer_idxs_3

array([1770, 2721, 3671,  269, 2941])

In [84]:
labels[test_answer_idxs_3]

Index(['kite', 'roost', 'whitehouse', 'bathtub', 'site'], dtype='object')