In [1]:
import pandas as pd
import numpy as np

In [6]:
y_df = pd.read_csv("y_dataframe.csv")

/var/folders/d1/xzw000453hgd1t8zbydcjg_80000gn/T/ipykernel_11169/2601136099.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  y_df = pd.read_csv("y_dataframe.csv")


In [38]:
y_train = y_df.iloc[:8859, 1:].to_numpy()

In [148]:
y_df

Unnamed: 0  1950s  1970  1971  2009  4-way  abandon  about  above  \
0                 0      0     0     0     0      0        0      0      0   
1                 1      0     0     0     0      0        0      0      0   
2                 2      0     0     0     0      0        0      0      0   
3                 3      0     0     0     0      0        0      0      0   
4                 4      0     0     0     0      0        0      0      0   
...             ...    ...   ...   ...   ...    ...      ...    ...    ...   
9836  X_test_id_977      0     0     0     0      0        0      0      0   
9837  X_test_id_978      0     0     0     0      0        0      0      0   
9838  X_test_id_979      0     0     0     0      0        0      0      0   
9839  X_test_id_980      0     0     0     0      0        0      0      0   
9840  X_test_id_981      0     0     0     0      0        0      0      0   

      abraham  ...  yogurt  york  you  young  younger  youth  zebra  zip  \
0           0  ...       0     0    0      0        0      0      0    0   
1           0  ...       0     0    0      0        0      0      0    0   
2           0  ...       0     0    0      0        0      0      0    0   
3           0  ...       0     0    0      0        0      0      0    0   
4           0  ...       0     0    0      0        0      0      1    0   
...       ...  ...     ...   ...  ...    ...      ...    ...    ...  ...   
9836        0  ...       0     0    0      0        0      0      0    0   
9837        0  ...       0     0    0      0        0      0      0    0   
9838        0  ...       0     0    0      0        0      0      0    0   
9839        0  ...       0     0    0      0        0      0      0    0   
9840        0  ...       0     0    0      0        0      0      0    0   

      zombie  zoo  
0          0    0  
1          0    0  
2          0    0  
3          0    0  
4          0    0  
...      ...  ...  
9836       0    0  
9837       0    0  
9838       0    0  
9839       0    0  
9840       0    0  

[9841 rows x 2638 columns]

In [4]:
y_df.drop(columns = ["Unnamed: 0"], inplace = True)

In [14]:
X_train = np.load("nsd_train_fmriavg_nsdgeneral_sub1.npy")

In [32]:
from sklearn.preprocessing import RobustScaler

In [152]:
scaler = RobustScaler()

In [153]:
X_scaled = scaler.fit_transform(X_train)

In [17]:
from tensorflow.keras import Sequential
from tensorflow.keras import layers

In [54]:
model = Sequential([layers.Dense(100, input_shape = (15724,), activation = "relu"),
                  layers.Dense(100, activation = "relu"),
                    layers.Dropout(0.4),
                  layers.Dense(200, activation = "relu"),
                    layers.Dropout(0.4),
                  layers.Dense(500, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(500, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(1000, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(2000, activation = "relu"),
                  layers.Dense(2637, activation = "sigmoid")])

In [55]:
model.compile(loss = "binary_crossentropy", optimizer = "adam")

In [56]:
model.fit(X_scaled, y_train, validation_split=0.1, batch_size = 32, epochs = 30)

Epoch 1/30


2023-06-09 12:00:21.147045: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-09 12:00:21.165550: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] PluggableGraphOptimizer failed: INVALID_ARGUMENT: Unparseable tensorflow.GraphDef proto
2023-06-09 12:00:21.173175: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] PluggableGraphOptimizer failed: INVALID_ARGUMENT: Unparseable tensorflow.GraphDef proto


250/250 [==============================] - 4s 12ms/step - loss: 0.0197 - val_loss: 0.0377


2023-06-09 12:00:24.269254: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-06-09 12:00:24.273760: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] PluggableGraphOptimizer failed: INVALID_ARGUMENT: Unparseable tensorflow.GraphDef proto
2023-06-09 12:00:24.275976: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] PluggableGraphOptimizer failed: INVALID_ARGUMENT: Unparseable tensorflow.GraphDef proto


Epoch 2/30
250/250 [==============================] - 3s 10ms/step - loss: 0.0094 - val_loss: 0.0267
Epoch 3/30
250/250 [==============================] - 3s 11ms/step - loss: 0.0088 - val_loss: 0.0157
Epoch 4/30
250/250 [==============================] - 3s 10ms/step - loss: 0.0084 - val_loss: 0.0105
Epoch 5/30
250/250 [==============================] - 3s 11ms/step - loss: 0.0081 - val_loss: 0.0088
Epoch 6/30
250/250 [==============================] - 3s 10ms/step - loss: 0.0078 - val_loss: 0.0082
Epoch 7/30
250/250 [==============================] - 3s 10ms/step - loss: 0.0076 - val_loss: 0.0080
Epoch 8/30
250/250 [==============================] - 3s 10ms/step - loss: 0.0074 - val_loss: 0.0079
Epoch 9/30
250/250 [==============================] - 3s 11ms/step - loss: 0.0073 - val_loss: 0.0078
Epoch 10/30
250/250 [==============================] - 3s 10ms/step - loss: 0.0071 - val_loss: 0.0078
Epoch 11/30
250/250 [==============================] - 3s 10ms/step - loss: 0.0070 - val_l

In [89]:
answer = model.predict(X_scaled[10].reshape(1,-1))

1/1 [==============================] - 0s 20ms/step


In [143]:
answer[answer>0.1]

array([0.45238286, 0.6659856 , 0.10593087, 0.19288626, 0.2133832 ,
       0.10100257, 0.22490627], dtype=float32)

In [137]:
answer_idxs = np.argpartition(answer[0],-4)[-4:]

In [144]:
answer_idxs

array([1280, 2064,  187,  383])

In [92]:
labels = y_df.columns[1:]

In [149]:
labels[answer_idxs]

Index(['lay', 'sit', 'bed', 'cat'], dtype='object')

In [150]:
X_test = np.load("nsd_test_fmriavg_nsdgeneral_sub1.npy")

In [155]:
X_test_scaled = scaler.transform(X_test)

In [156]:
X_test_scaled[0]

array([-1.28444441, -0.48185293, -0.05411858, ...,  0.12920738,
       -0.63977899, -0.8584444 ])

In [195]:
test_answer = model.predict(X_test_scaled[300].reshape(1,-1))

1/1 [==============================] - 0s 14ms/step


In [196]:
test_answer

array([[9.5885471e-06, 5.5025398e-06, 3.6801330e-06, ..., 1.5138574e-05,
        1.5306929e-05, 8.5355623e-06]], dtype=float32)

In [193]:
test_answer_idxs = np.argpartition(test_answer[0],-4)[-4:]

In [194]:
labels[test_answer_idxs]

Index(['wall', 'build', 'tower', 'clock'], dtype='object')