In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import RobustScaler, StandardScaler
from tensorflow.keras import Sequential
from tensorflow.keras import layers


2023-06-12 09:34:57.191419: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-12 09:34:57.287997: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-06-12 09:34:57.703096: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-06-12 09:34:57.703192: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or 

In [2]:
y_df = pd.read_csv("../data/y_dataframe.csv")

/tmp/ipykernel_19116/4167803891.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  y_df = pd.read_csv("../data/y_dataframe.csv")


In [3]:
y_train = y_df.iloc[:8859, 1:].to_numpy()

In [4]:
y_df

Unnamed: 0  1950s  1970  1971  2009  4-way  abandon  about  above  \
0                 0      0     0     0     0      0        0      0      0   
1                 1      0     0     0     0      0        0      0      0   
2                 2      0     0     0     0      0        0      0      0   
3                 3      0     0     0     0      0        0      0      0   
4                 4      0     0     0     0      0        0      0      0   
...             ...    ...   ...   ...   ...    ...      ...    ...    ...   
9836  X_test_id_977      0     0     0     0      0        0      0      0   
9837  X_test_id_978      0     0     0     0      0        0      0      0   
9838  X_test_id_979      0     0     0     0      0        0      0      0   
9839  X_test_id_980      0     0     0     0      0        0      0      0   
9840  X_test_id_981      0     0     0     0      0        0      0      0   

      abraham  ...  yogurt  york  you  young  younger  youth  zebra  zip  \
0           0  ...       0     0    0      0        0      0      0    0   
1           0  ...       0     0    0      0        0      0      0    0   
2           0  ...       0     0    0      0        0      0      0    0   
3           0  ...       0     0    0      0        0      0      0    0   
4           0  ...       0     0    0      0        0      0      1    0   
...       ...  ...     ...   ...  ...    ...      ...    ...    ...  ...   
9836        0  ...       0     0    0      0        0      0      0    0   
9837        0  ...       0     0    0      0        0      0      0    0   
9838        0  ...       0     0    0      0        0      0      0    0   
9839        0  ...       0     0    0      0        0      0      0    0   
9840        0  ...       0     0    0      0        0      0      0    0   

      zombie  zoo  
0          0    0  
1          0    0  
2          0    0  
3          0    0  
4          0    0  
...      ...  ...  
9836       0    0  
9837       0    0  
9838       0    0  
9839       0    0  
9840       0    0  

[9841 rows x 2638 columns]

In [5]:
y_df.drop(columns = ["Unnamed: 0"], inplace = True)

In [6]:
y_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [7]:
X_train = np.load("../data/nsd_train_fmriavg_nsdgeneral_sub1.npy")

In [8]:
scaler = RobustScaler()

In [9]:
X_train

array([[-2.08666672e+02,  1.03333330e+01,  2.22000000e+02, ...,
         5.08000000e+02,  1.15800000e+03,  7.71666687e+02],
       [ 6.25333313e+02,  1.05000000e+02,  2.61000000e+02, ...,
         4.95000000e+02,  7.87333313e+02,  5.37666687e+02],
       [ 7.84000000e+02, -9.30000000e+01, -3.46666679e+01, ...,
         3.33333343e-01,  2.02666672e+02,  2.63000000e+02],
       ...,
       [ 7.36000000e+02, -4.62000000e+02,  3.00000000e+02, ...,
         1.97000000e+02,  7.04000000e+02, -1.45000000e+02],
       [ 1.10250000e+03, -1.47000000e+02,  2.94000000e+02, ...,
         2.70500000e+02,  7.33000000e+02,  2.32000000e+02],
       [ 2.00000000e+02, -4.57000000e+02,  1.54000000e+02, ...,
         3.20000000e+01,  4.87000000e+02,  1.94000000e+02]])

In [10]:
X_scaled = scaler.fit_transform(X_train)

In [11]:
X_scaled.shape

(8859, 15724)

In [12]:
y_train.shape

(8859, 2637)

In [13]:
model = Sequential([layers.Dense(100, input_shape = (15724,), activation = "relu"),
                  layers.Dense(100, activation = "relu"),
                    layers.Dropout(0.4),
                  layers.Dense(200, activation = "relu"),
                    layers.Dropout(0.4),
                  layers.Dense(500, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(500, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(1000, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(2000, activation = "relu"),
                  layers.Dense(2637, activation = "sigmoid")])

2023-06-12 09:35:26.886019: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-06-12 09:35:27.051436: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2023-06-12 09:35:27.051452: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-06-12 09:35:27.052603: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (o

In [14]:
model.compile(loss = "binary_crossentropy", optimizer = "adam")

In [15]:
from tensorflow.keras.callbacks import EarlyStopping
es = EarlyStopping(patience=7,restore_best_weights = True)

model.fit(X_scaled, y_train, validation_split=0.1, batch_size = 32, epochs = 40, callbacks=[es])

2023-06-12 09:35:34.686564: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 501469808 exceeds 10% of free system memory.
2023-06-12 09:35:35.027665: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 168198408 exceeds 10% of free system memory.


Epoch 1/40
250/250 [==============================] - 6s 22ms/step - loss: 0.0200 - val_loss: 0.0464
Epoch 2/40
250/250 [==============================] - 5s 21ms/step - loss: 0.0096 - val_loss: 0.0167
Epoch 3/40
250/250 [==============================] - 5s 20ms/step - loss: 0.0089 - val_loss: 0.0085
Epoch 4/40
250/250 [==============================] - 5s 20ms/step - loss: 0.0085 - val_loss: 0.0085
Epoch 5/40
250/250 [==============================] - 5s 20ms/step - loss: 0.0084 - val_loss: 0.0084
Epoch 6/40
250/250 [==============================] - 5s 20ms/step - loss: 0.0083 - val_loss: 0.0083
Epoch 7/40
250/250 [==============================] - 5s 20ms/step - loss: 0.0082 - val_loss: 0.0083
Epoch 8/40
250/250 [==============================] - 5s 20ms/step - loss: 0.0080 - val_loss: 0.0081
Epoch 9/40
250/250 [==============================] - 5s 20ms/step - loss: 0.0079 - val_loss: 0.0080
Epoch 10/40
250/250 [==============================] - 5s 20ms/step - loss: 0.0077 - val_lo

In [16]:
answer = model.predict(X_scaled[2].reshape(1,-1))

1/1 [==============================] - 0s 72ms/step


In [17]:
answer[answer>0.1]

array([0.12492863, 0.10666753], dtype=float32)

In [18]:
answer_idxs = np.argpartition(answer[0],-4)[-4:]

In [19]:
answer_idxs

array([ 703, 2188, 1366, 1668])

In [20]:
labels = y_df.columns[1:]

In [21]:
labels[answer_idxs]

Index(['doll', 'star', 'maneuver', 'pepper'], dtype='object')

In [22]:
X_test = np.load("../data/nsd_test_fmriavg_nsdgeneral_sub1.npy")

In [23]:
X_test_scaled = scaler.transform(X_test)

In [24]:
X_test_scaled[0]

array([-1.28444441, -0.48185293, -0.05411858, ...,  0.12920738,
       -0.63977899, -0.8584444 ])

In [25]:
test_answer = model.predict(X_test_scaled[400].reshape(1,-1))

1/1 [==============================] - 0s 14ms/step


In [26]:
test_answer[0]

array([3.0354238e-05, 4.9873161e-06, 1.2966197e-05, ..., 5.4523414e-05,
       2.3517887e-06, 4.5631090e-04], dtype=float32)

In [27]:
test_answer_idxs = np.argpartition(test_answer[0],-4)[-4:]

In [28]:
labels[test_answer_idxs]

Index(['planner', 'body', 'airport', 'waterbird'], dtype='object')