In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import RobustScaler, StandardScaler
from tensorflow.keras import Sequential
from tensorflow.keras import layers


2023-06-09 17:16:40.365442: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-09 17:16:40.669603: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-06-09 17:16:41.571579: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-06-09 17:16:41.571661: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or 

In [5]:
y_df = pd.read_csv("../data/y_dataframe.csv")

/tmp/ipykernel_5080/4167803891.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  y_df = pd.read_csv("../data/y_dataframe.csv")


In [6]:
y_train = y_df.iloc[:8859, 1:].to_numpy()

In [9]:
y_df

Unnamed: 0  1950s  1970  1971  2009  4-way  abandon  about  above  \
0                 0      0     0     0     0      0        0      0      0   
1                 1      0     0     0     0      0        0      0      0   
2                 2      0     0     0     0      0        0      0      0   
3                 3      0     0     0     0      0        0      0      0   
4                 4      0     0     0     0      0        0      0      0   
...             ...    ...   ...   ...   ...    ...      ...    ...    ...   
9836  X_test_id_977      0     0     0     0      0        0      0      0   
9837  X_test_id_978      0     0     0     0      0        0      0      0   
9838  X_test_id_979      0     0     0     0      0        0      0      0   
9839  X_test_id_980      0     0     0     0      0        0      0      0   
9840  X_test_id_981      0     0     0     0      0        0      0      0   

      abraham  ...  yogurt  york  you  young  younger  youth  zebra  zip  \
0           0  ...       0     0    0      0        0      0      0    0   
1           0  ...       0     0    0      0        0      0      0    0   
2           0  ...       0     0    0      0        0      0      0    0   
3           0  ...       0     0    0      0        0      0      0    0   
4           0  ...       0     0    0      0        0      0      1    0   
...       ...  ...     ...   ...  ...    ...      ...    ...    ...  ...   
9836        0  ...       0     0    0      0        0      0      0    0   
9837        0  ...       0     0    0      0        0      0      0    0   
9838        0  ...       0     0    0      0        0      0      0    0   
9839        0  ...       0     0    0      0        0      0      0    0   
9840        0  ...       0     0    0      0        0      0      0    0   

      zombie  zoo  
0          0    0  
1          0    0  
2          0    0  
3          0    0  
4          0    0  
...      ...  ...  
9836       0    0  
9837       0    0  
9838       0    0  
9839       0    0  
9840       0    0  

[9841 rows x 2638 columns]

In [10]:
y_df.drop(columns = ["Unnamed: 0"], inplace = True)

In [16]:
y_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [17]:
X_train = np.load("../data/nsd_train_fmriavg_nsdgeneral_sub1.npy")

In [41]:
scaler = RobustScaler()

In [42]:
X_train

array([[-2.08666672e+02,  1.03333330e+01,  2.22000000e+02, ...,
         5.08000000e+02,  1.15800000e+03,  7.71666687e+02],
       [ 6.25333313e+02,  1.05000000e+02,  2.61000000e+02, ...,
         4.95000000e+02,  7.87333313e+02,  5.37666687e+02],
       [ 7.84000000e+02, -9.30000000e+01, -3.46666679e+01, ...,
         3.33333343e-01,  2.02666672e+02,  2.63000000e+02],
       ...,
       [ 7.36000000e+02, -4.62000000e+02,  3.00000000e+02, ...,
         1.97000000e+02,  7.04000000e+02, -1.45000000e+02],
       [ 1.10250000e+03, -1.47000000e+02,  2.94000000e+02, ...,
         2.70500000e+02,  7.33000000e+02,  2.32000000e+02],
       [ 2.00000000e+02, -4.57000000e+02,  1.54000000e+02, ...,
         3.20000000e+01,  4.87000000e+02,  1.94000000e+02]])

In [43]:
X_scaled = scaler.fit_transform(X_train)

In [44]:
X_scaled.shape

(8859, 15724)

In [45]:
model = Sequential([layers.Dense(100, input_shape = (15724,), activation = "relu"),
                  layers.Dense(100, activation = "relu"),
                    layers.Dropout(0.4),
                  layers.Dense(200, activation = "relu"),
                    layers.Dropout(0.4),
                  layers.Dense(500, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(500, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(1000, activation = "relu"),
                    layers.Dropout(0.4),
                    layers.Dense(2000, activation = "relu"),
                  layers.Dense(2637, activation = "sigmoid")])

In [46]:
model.compile(loss = "binary_crossentropy", optimizer = "adam")

In [47]:
from tensorflow.keras.callbacks import EarlyStopping
es = EarlyStopping(patience=7,restore_best_weights = True)

model.fit(X_scaled, y_train, validation_split=0.1, batch_size = 32, epochs = 40, callbacks=[es])

2023-06-09 17:23:38.233232: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 501469808 exceeds 10% of free system memory.


Epoch 1/40
250/250 [==============================] - 6s 22ms/step - loss: 0.0201 - val_loss: 0.0400
Epoch 2/40
250/250 [==============================] - 5s 21ms/step - loss: 0.0096 - val_loss: 0.0191
Epoch 3/40
250/250 [==============================] - 5s 20ms/step - loss: 0.0089 - val_loss: 0.0085
Epoch 4/40
250/250 [==============================] - 5s 20ms/step - loss: 0.0085 - val_loss: 0.0084
Epoch 5/40
250/250 [==============================] - 5s 21ms/step - loss: 0.0084 - val_loss: 0.0084
Epoch 6/40
250/250 [==============================] - 5s 20ms/step - loss: 0.0082 - val_loss: 0.0082
Epoch 7/40
250/250 [==============================] - 5s 20ms/step - loss: 0.0081 - val_loss: 0.0080
Epoch 8/40
250/250 [==============================] - 5s 20ms/step - loss: 0.0079 - val_loss: 0.0080
Epoch 9/40
250/250 [==============================] - 5s 20ms/step - loss: 0.0077 - val_loss: 0.0079
Epoch 10/40
250/250 [==============================] - 5s 21ms/step - loss: 0.0076 - val_lo

In [48]:
answer = model.predict(X_scaled[2].reshape(1,-1))

1/1 [==============================] - 0s 51ms/step


In [49]:
answer[answer>0.1]

array([0.10554398, 0.2379632 , 0.2291145 , 0.12225763, 0.2550553 ,
       0.13217291, 0.12515576, 0.16752219], dtype=float32)

In [50]:
answer_idxs = np.argpartition(answer[0],-4)[-4:]

In [51]:
answer_idxs

array([2539, 1464, 1366, 1668])

In [52]:
labels = y_df.columns[1:]

In [53]:
labels[answer_idxs]

Index(['walker', 'motorcyclist', 'maneuver', 'pepper'], dtype='object')

In [54]:
X_test = np.load("../data/nsd_test_fmriavg_nsdgeneral_sub1.npy")

In [55]:
X_test_scaled = scaler.transform(X_test)

In [56]:
X_test_scaled[0]

array([-1.28444441, -0.48185293, -0.05411858, ...,  0.12920738,
       -0.63977899, -0.8584444 ])

In [82]:
test_answer = model.predict(X_test_scaled[400].reshape(1,-1))

1/1 [==============================] - 0s 15ms/step


In [83]:
test_answer[0]

array([8.9370023e-06, 8.0717682e-06, 8.4809144e-06, ..., 3.3329750e-05,
       4.7343824e-06, 3.5786626e-04], dtype=float32)

In [84]:
test_answer_idxs = np.argpartition(test_answer[0],-4)[-4:]

In [85]:
labels[test_answer_idxs]

Index(['waterbird', 'airport', 'body', 'foam'], dtype='object')