In [1]:
import pandas as pd
import numpy as np
from tensorflow.keras import Sequential, layers, models
from sklearn.preprocessing import MinMaxScaler, RobustScaler
from tensorflow.keras.callbacks import EarlyStopping
import h5py as h5
import matplotlib.pyplot as plt
from sklearn.preprocessing import RobustScaler

2023-06-14 13:09:14.658804: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-14 13:09:14.952131: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-06-14 13:09:15.701307: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-06-14 13:09:15.701390: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or 

### Import X, y

In [3]:
y_df = pd.read_csv("../data/y_dataframe_2.csv")
X_test = np.load("../data/nsd_test_fmriavg_nsdgeneral_sub1.npy")
X_train = np.load("../data/nsd_train_fmriavg_nsdgeneral_sub1.npy")

/tmp/ipykernel_2532/4240021758.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  y_df = pd.read_csv("../data/y_dataframe_2.csv")


### Drop columns

In [4]:
y_df.drop(columns = ["Unnamed: 0", "Unnamed: 1"], inplace = True)


In [5]:
y_df

1950  1950s  1970  1971  2009  2010  4way  abandon  ability  ablaze  \
0        0      0     0     0     0     0     0        0        0       0   
1        0      0     0     0     0     0     0        0        0       0   
2        0      0     0     0     0     0     0        0        0       0   
3        0      0     0     0     0     0     0        0        0       0   
4        0      0     0     0     0     0     0        0        0       0   
...    ...    ...   ...   ...   ...   ...   ...      ...      ...     ...   
9836     0      0     0     0     0     0     0        0        0       0   
9837     0      0     0     0     0     0     0        0        0       0   
9838     0      0     0     0     0     0     0        0        0       0   
9839     0      0     0     0     0     1     0        0        0       0   
9840     0      0     0     0     0     0     0        0        0       0   

      ...  young  younger  youre  youth  zebra  zigzag  zip  zombie  zoo  zoom  
0     ...      0        0      0      0      0       0    0       0    0     0  
1     ...      0        0      0      0      0       0    0       0    0     0  
2     ...      0        0      0      0      0       0    0       0    0     0  
3     ...      0        0      0      0      0       0    0       0    0     0  
4     ...      0        0      0      0      1       0    0       0    0     0  
...   ...    ...      ...    ...    ...    ...     ...  ...     ...  ...   ...  
9836  ...      0        0      0      0      0       0    0       0    0     0  
9837  ...      0        0      0      0      0       0    0       0    0     0  
9838  ...      0        0      0      0      0       0    0       0    0     0  
9839  ...      0        0      0      0      0       0    0       0    0     0  
9840  ...      0        0      0      0      0       0    0       0    0     0  

[9841 rows x 3759 columns]

### Check shape & labels

In [10]:
y_train = y_df.iloc[:8859].to_numpy()
print(y_train)
print(y_train.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(8859, 3759)


In [11]:
labels=y_df.columns
print(labels)

Index(['1950', '1950s', '1970', '1971', '2009', '2010', '4way', 'abandon',
       'ability', 'ablaze',
       ...
       'young', 'younger', 'youre', 'youth', 'zebra', 'zigzag', 'zip',
       'zombie', 'zoo', 'zoom'],
      dtype='object', length=3759)


### Scale

In [8]:
scaler = RobustScaler()
X_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Model


In [9]:
model_2L = Sequential([layers.Dense(100, input_shape = (15724,), activation = "relu"),
                  layers.Dense(100, activation = "relu"),
                    
                  layers.Dense(200, activation = "relu"),
                    
                  layers.Dense(500, activation = "relu"),
                    
                    layers.Dense(500, activation = "relu"),
                    
                    layers.Dense(1000, activation = "relu"),
                    
                    layers.Dense(2000, activation = "relu"),
                      
                      layers.Dense(1000, activation = "relu"),
                      
                      layers.Dense(500, activation = "relu"),
                      
                      layers.Dense(200, activation = "relu"),
                      
                      layers.Dense(100, activation = "relu"),
                      
                  layers.Dense(3759, activation = "sigmoid")])



2023-06-14 13:10:30.160742: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-06-14 13:10:30.626924: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2023-06-14 13:10:30.628921: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-06-14 13:10:30.652028: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (o

In [12]:
model_2L.compile(loss = "binary_crossentropy", optimizer = "adam")
es = EarlyStopping(patience=20,restore_best_weights = True)

In [ ]:
history_2L = model_2L.fit(X_scaled, y_train, validation_split=0.15, batch_size = 32, epochs = 120, callbacks=[es])
# model_2L.fit(X_scaled, y_train, validation_split=0.15, batch_size = 32, epochs = 30)

In [ ]:
# model2 = models.load_model('C:\\Users\\Admin\\Documents\\MindSee\\models\\model2')
# model2.summary()

In [ ]:
images_file = h5.File("C:\\Users\\Admin\\Documents\\MindSee\\data\\selected_test_images.hdf5", "r")
stim_list_test=np.load('C:\\Users\\Admin\\Documents\\MindSee\\data\\nsd_test_stim_list1.npy')
stim_list_train=np.load('C:\\Users\\Admin\\Documents\\MindSee\\data\\subj01_nsd_train_stim_list1.npy')
# train_caps=np.load('drive/MyDrive/data/nsd_train_cap_sub1.npy')
test_caps=np.load('C:\\Users\\Admin\\Documents\\MindSee\\data\\nsd_test_cap_sub1.npy')
X_test_dataframe = pd.read_csv('C:\\Users\\Admin\\Documents\\MindSee\\data\\df_test.csv')
df_test_idx_caps=X_test_dataframe[['Image_index', 'test_caps_processed']]

In [ ]:
def pred(model_name, idx):
    test_answer=model_name.predict(X_test_scaled[idx].reshape(1,-1))
    test_answer_idxs = np.argpartition(test_answer[0],-5)[-5:]
    answer=labels[test_answer_idxs]
    return answer

In [ ]:
idx=12
test_index=stim_list_test[idx]
#model 2L
print(pred(model_2L, idx))
#show image
plt.imshow(images_file[str(test_index)])
plt.show()